### PR TITLE
Merge latest codespeed/master from upstream into speed.pypy.org 

### PR DESCRIPTION
**Pull request by mattip**
I tried this out locally to iron out the fine points. Major breaking changes from the existing site:
- the module has moved from `example` to `sample_project`
  - are there files in `example that still need to move (like `wsgi.py`)?
 - should I copy all the `sample_project` to `example` so we do not have to change deployment recipes? Speed.python.org uses neither.
- the database model is too different, migration on top of the old db fails
  - however manage.py dumpdata > cleanup > manage.py loaddata works. I have a file of the middle stage ready to go
  - this means we need to change the table names or drop the existing tables

### CODE REVIEW

**Comment by vstinner** [comment]
Sorry I don't understand which project is the upstream now. Why are there 3 GitHub projects?
* https://github.com/python/codespeed
* https://github.com/mattip/codespeed
* https://github.com/alex/codespeed

If https://github.com/mattip/codespeed is the upstream, why not just remove this one for example?

**Comment by mattip** [comment]
Upstream is the generic tobami/codespeed. This one should be the python fork used to deploy the two websites.

**Comment by ewdurbin** [comment]
> * the module has moved from `example` to `sample_project`

Probably a good idea to name the module `speed_pypy` similar to how the `speed.python.org` branch is setup.

>   * are there files in `example that still need to move (like `wsgi.py`)?

Not that I'm aware of, `wsgi.py` is there to give an entry point for gunicorn.

> * should I copy all the `sample_project` to `example` so we do not have to change deployment recipes? Speed.python.org uses neither.

No, we can update [the app entrypoint](https://github.com/python/psf-salt/blob/3a0cdc14b670d784ae93b455860ddaabf989bc58/pillar/base/codespeed.sls#L26).

>   * however manage.py dumpdata > cleanup > manage.py loaddata works. I have a file of the middle stage ready to go
>   * this means we need to change the table names or drop the existing tables

This can be accommodated, though I'm not sure what cleanup is referencing here.

**Comment by mattip** [comment]
cleanup means I edited the json file to remove all the tables and information no longer relevant for the new data model. That file is ready to go

**Comment by ewdurbin** [comment]
@mattip I opened the above ref'd PR to point to speed_pypy as the module. that and the addition of a wsgi.py are all I'm aware of that we need before merging them both.

**Comment by mattip** [comment]
added the wsgi.py from `example` and all the files from `sample_project` to `speed_pypy`

**Pull request merged**
